/** 随身版语音输入：转发共享模块，保持既有 import 路径稳定。 */
export {
  DEFAULT_WAKE_PHRASE,
  VOICE_RESTART_DELAY_MS,
  DICTATION_SILENCE_MS,
  containsWakePhrase,
  containsConfiguredWakePhrase,
  transcriptAfterConfiguredWakePhrase,
  createSpeechRecognition,
  isSpeechInputSupported,
  isSpeechOutputSupported,
  latestTranscriptFromEvent,
  normalizeVoiceText,
  pickBestAlternative,
  transcriptAfterWakePhrase,
  transcriptFromEvent,
  createDictationController,
  applyHotwordCorrections,
  memberNameHotwordPairs,
  endsWithContinuationCue,
  queryMicrophonePermission,
  speakText,
  stopSpeaking,
  pauseSpeaking,
  resumeSpeaking,
  isSpeakingPaused,
  skipSpeakingSegment,
  jumpSpeakingSegment,
  getSpeakingSegments,
  getSpeakingIndex,
  listChineseVoices,
  pickPreferredChineseVoice,
  resolveSpeechVoice,
  prepareSpeechText,
  splitSpeechSegments,
  waitForVoices,
  inspectChineseVoicePacks,
  runVoicePreflight,
  loadChatSession,
  loadChatDraft,
  saveChatSession,
  saveChatDraft,
  clearChatSession,
  clearChatDraft,
  clearChatSessionsForActor,
  createChatThread,
  deleteChatThread,
  getActiveChatThreadId,
  getAssistantSessionId,
  listChatThreads,
  regenerateAssistantSessionId,
  renameChatThread,
  setActiveChatThread,
  sessionEntryToStored,
  touchChatThread,
  loadVoicePreferences,
  saveVoicePreferences,
  DEFAULT_VOICE_PREFERENCES,
  SILENCE_PRESETS,
  WAKE_PHRASE_PRESETS,
  validateWakePhrase,
  sanitizeWakePhraseInput,
  matchVoiceCommand,
  createAutoSendScheduler,
  createSendConfirmGate,
  DEFAULT_AUTO_SEND_DELAY_MS,
  VOICE_COMMAND_HINT,
  AUTO_SEND_PRESETS,
  type DictationController,
  type DictationMode,
  type DictationHandlers,
  type SpeechRecognitionLike,
  type SpeechRecognitionEventLike,
  type SpeechRecognitionErrorEventLike,
  type SpeechRecognitionResultLike,
  type StoredChatEntry,
  type ChatThreadMeta,
  type VoicePackReport,
  type SpeakOptions,
  type SpeakProgress,
  type SpeechVoiceLike,
  type VoicePreferences,
  type VoicePreflightReport,
  type VoiceCommandId,
  type HotwordPair,
} from '@hct/voice'
