import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Fingerprint, HeartPulse, Home, Lock, Shield, UserPlus } from 'lucide-react'
import './auth-page.css'

const stages = ['账户创建', '家庭设置', '隐私确认']
const Brand = () => <div className="auth-brand"><HeartPulse size={26}/><b>HomeCare Twin</b></div>
const Field = ({label, children}) => <label className="auth-field"><b>{label}</b>{children}</label>
function Stepper({step}) { return <div className="auth-stepper">{stages.map((name, i) => <div className="auth-step" key={name}><span className={i + 1 <= step ? 'on' : ''}>{i + 1 < step ? <Check size={15}/> : i + 1}</span><b>{name}</b>{i < 2 && <i className={i + 1 < step ? 'on' : ''}/>}</div>)}</div> }

export function AuthPage({onComplete}) {
  const [register, setRegister] = useState(false), [tab, setTab] = useState('phone'), [step, setStep] = useState(1), [seconds, setSeconds] = useState(0), [agreed, setAgreed] = useState(false), [account, setAccount] = useState(''), [password, setPassword] = useState(''), [loginError, setLoginError] = useState('')
  const sendCode = () => { if (seconds) return; setSeconds(60); const timer = setInterval(() => setSeconds(value => { if (value < 2) { clearInterval(timer); return 0 }; return value - 1 }), 1000) }
  const Phone = () => <Field label="手机号码"><div className="auth-phone"><b>+86</b><input required inputMode="numeric" placeholder="请输入手机号码" /></div></Field>
  const Code = () => <Field label="验证码"><div className="auth-code"><input required maxLength="6" placeholder="6位验证码"/><button type="button" onClick={sendCode}>{seconds ? `${seconds}s 后重试` : '获取验证码'}</button></div></Field>
  if (!register) return <main className="auth-login"><aside className="auth-art"><Brand/><div className="auth-orbit"><Shield size={104}/><span><HeartPulse size={29}/></span></div><div><h2>守护全家健康</h2><p>融合专业级医疗精度与家庭温度，全天候守护您的挚爱。</p></div></aside><section className="auth-panel"><div className="mobile-brand"><Brand/></div><form onSubmit={event => { event.preventDefault(); if (tab !== 'password' || (account === 'demo@homecare.local' && password === 'HomeCare123!')) { setLoginError(''); onComplete() } else { setLoginError('账号或密码不正确') } }}><div><h1>欢迎回来，家健镜</h1><p>请登录以查看您的家庭健康控制台。</p></div><nav className="auth-tabs"><button className={tab === 'phone' ? 'selected' : ''} type="button" onClick={() => setTab('phone')}>手机号登录</button><button className={tab === 'invite' ? 'selected' : ''} type="button" onClick={() => setTab('invite')}>家属邀请码</button><button className={tab === 'password' ? 'selected' : ''} type="button" onClick={() => { setTab('password'); setLoginError('') }}>账号密码登录</button></nav>{tab === 'phone' ? <><Phone/><Code/></> : tab === 'password' ? <><Field label="账号"><input required value={account} onChange={event => setAccount(event.target.value)} placeholder="请输入账号"/></Field><Field label="密码"><input required type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="请输入密码"/></Field><p className="auth-demo">演示账号：demo@homecare.local　密码：HomeCare123!</p>{loginError && <p className="auth-error">{loginError}</p>}</> : <><Field label="家庭邀请码"><input required placeholder="请输入 8 位邀请码"/></Field><Field label="您的姓名"><input required placeholder="请输入姓名"/></Field></>}<button className="primary">快速进入 <ArrowRight size={17}/></button><div className="or">或</div><button type="button" className="biometric"><Fingerprint size={20}/>通过生物识别登录</button><p className="switch">还没有家庭账户？<button type="button" onClick={() => setRegister(true)}>开始创建</button></p><div className="secure"><Lock size={17}/><span>您的健康数据完全存储在本地家庭网络中，通过端到端加密保护。我们绝不会将您的敏感数据上传至云端。</span></div></form></section></main>
  const next = event => { event.preventDefault(); setStep(value => value + 1) }
  return <main className="register"><section className="register-card"><header><button type="button" className="auth-login-link" onClick={() => { setRegister(false); setStep(1) }}><ArrowLeft size={17}/>返回登录</button><div><h1>{step === 1 ? '创建您的家庭账户' : step === 2 ? '完善您的家庭档案' : '本地优先与隐私加密确认'}</h1><p>第 {step} 步，共 3 步：{stages[step - 1]}</p></div><Brand/></header><Stepper step={step}/>{step === 1 && <form className="body" onSubmit={next}><Phone/><Code/><Field label="设置昵称"><input required placeholder="例如：小林"/></Field><footer><span/><button className="primary">下一步 <ArrowRight size={17}/></button></footer></form>}{step === 2 && <form className="body" onSubmit={next}><div className="grid"><Field label="您在家庭中的角色"><input required placeholder="例如：女儿"/></Field><Field label="家庭名称"><input required placeholder="例如：张家的健康中心"/></Field></div><button type="button" className="add"><span><UserPlus size={24}/></span><b>添加第一位家庭成员</b><small>添加您想关照的长辈或其他家庭成员</small></button><footer><button className="back" type="button" onClick={() => setStep(1)}><ArrowLeft size={17}/>返回</button><button className="primary">下一步 <ArrowRight size={17}/></button></footer></form>}{step === 3 && <section className="body privacy"><div className="shield"><Shield size={70}/><Home size={23}/></div><h2>本地优先与隐私加密确认</h2>{[['数据不出家门','您的所有健康数据将优先存储在本地网关，确保家庭数据主权。'],['端到端同步加密','设备间同步全程加密，中继服务无法读取。'],['AI 本地运行','健康趋势分析与风险预警均由本地轻量模型完成。']].map(([title, text], i) => <article key={title}><span>{i + 1}</span><div><b>{title}</b><p>{text}</p></div></article>)}<label className="consent"><input type="checkbox" checked={agreed} onChange={event => setAgreed(event.target.checked)}/>我已了解并同意本地数据保护说明</label><footer><button type="button" className="back" onClick={() => setStep(2)}><ArrowLeft size={17}/>返回</button><button className="primary" disabled={!agreed} onClick={onComplete}><Shield size={17}/>开启安全守护</button></footer></section>}</section><p className="copyright">© 2024 HomeCare Twin. Your health data stays on your local network.</p></main>
}
