import { useState } from 'react'
import { BellRing, ChevronRight, CircleHelp, ContactRound, Database, Fingerprint, HeartPulse, Laptop, LockKeyhole, Network, Plus, ShieldCheck, Smartphone, UsersRound } from 'lucide-react'
import { PageFrame } from './template-pages.jsx'

function Toggle({ initial = true, label }) {
  const [enabled, setEnabled] = useState(initial)
  return <button className={`setting-toggle ${enabled ? 'enabled' : ''}`} onClick={() => setEnabled(!enabled)} aria-label={label} aria-pressed={enabled}><span /></button>
}

const Item = ({ icon: Icon, title, detail, action, href }) => <a className="settings-row" href={href || '#系统设置'}><span className="settings-row-icon"><Icon size={20} /></span><span className="settings-row-copy"><strong>{title}</strong><small>{detail}</small></span>{action || <ChevronRight size={19} />}</a>

export function SettingsPage() {
  return <PageFrame title="系统设置"><div className="settings-intro"><p className="eyebrow">HomeCare Twin</p><h1>系统设置</h1><p>管理个人偏好、家庭协作方式与本地健康数据安全。</p></div><div className="settings-layout"><div className="settings-main"><section className="settings-group"><h2>个人偏好</h2><Item icon={BellRing} title="通知与提醒" detail="药物、健康事件与设备同步提醒" action={<Toggle label="通知与提醒" />} /><Item icon={Smartphone} title="显示与语言" detail="简体中文 · 跟随系统深浅色模式" /><Item icon={CircleHelp} title="帮助与反馈" detail="使用帮助、问题反馈与新功能说明" /></section><section className="settings-group"><h2>家庭管理</h2><Item icon={ContactRound} title="紧急联系人" detail="管理紧急情况下的首要通知对象" href="#紧急联系人" /><Item icon={UsersRound} title="照护权限" detail="分配家庭成员与医生的访问范围" href="#权限" /></section><section className="settings-group"><h2>关于与支持</h2><Item icon={Database} title="导出家庭数据" detail="导出仅保存在本地设备的健康记录" /><Item icon={CircleHelp} title="关于家健镜" detail="版本 1.0.0 · 服务条款与隐私说明" /></section></div><aside className="settings-side"><section className="security-panel"><div className="security-panel-head"><div><p>本地优先</p><h2>隐私与安全仪表板</h2></div><ShieldCheck size={31} /></div><div className="security-item"><div><Database size={19} /><span><strong>本地数据存储</strong><small>所有健康数据保留在家庭设备中</small></span></div><Toggle label="本地数据存储" /></div><div className="security-item"><div><Fingerprint size={19} /><span><strong>生物识别锁定</strong><small>打开设置前需要验证身份</small></span></div><Toggle label="生物识别锁定" /></div><div className="security-item"><div><LockKeyhole size={19} /><span><strong>加密备份</strong><small>本地加密后备份至指定设备</small></span></div><Toggle initial={false} label="加密备份" /></div></section><section className="device-panel"><div className="section-heading"><h3><Laptop size={20} /> 设备连接</h3><button className="add-device"><Plus size={15} /> 添加设备</button></div><div className="device-row"><span><HeartPulse size={20} /></span><div><strong>Omron 血压计 (BP-700)</strong><small>已连接 · 最后同步于 10 分钟前</small></div><b>在线</b></div><div className="device-row"><span><Network size={20} /></span><div><strong>Accu-Chek 血糖仪</strong><small>已连接 · 每日自动同步</small></div><b>在线</b></div><div className="device-row"><span><Laptop size={20} /></span><div><strong>本地网络同步</strong><small>家庭设备发现已开启</small></div><b>安全</b></div></section></aside></div></PageFrame>
}

export function EmergencyContactsPage() {
  const [primary, setPrimary] = useState('林建国')
  return <PageFrame title="紧急联系人设置"><div className="settings-intro contacts-intro"><a href="#系统设置">← 返回系统设置</a><p className="eyebrow">家庭安全</p><h1>紧急联系人设置</h1><p>当系统检测到需要立即关注的健康风险时，会按照下列顺序通知联系人。</p></div><div className="contacts-layout"><section className="contact-primary"><div className="contact-primary-top"><div className="contact-avatar">林</div><div><p>首要联系人</p><h2>{primary}</h2><span>父亲 · 已验证手机号</span></div><button onClick={() => setPrimary(primary === '林建国' ? '王小明' : '林建国')}>更换</button></div><div className="contact-details"><div><span>联系电话</span><strong>138 0013 8849</strong></div><div><span>通知方式</span><strong>电话、短信与应用通知</strong></div><div><span>覆盖范围</span><strong>高风险健康事件</strong></div></div></section><section className="contact-list-panel"><div className="section-heading"><h3><UsersRound size={20} /> 通知顺序</h3><button className="add-contact"><Plus size={16} /> 添加联系人</button></div><article className="contact-row"><b>1</b><div className="contact-avatar small">林</div><div><strong>林建国</strong><small>父亲 · 电话、短信、应用通知</small></div><span>首要</span><ChevronRight size={19} /></article><article className="contact-row"><b>2</b><div className="contact-avatar small lilac">王</div><div><strong>王小明</strong><small>家庭医生 · 应用通知</small></div><span>备选</span><ChevronRight size={19} /></article><article className="contact-row"><b>3</b><div className="contact-avatar small rose">陈</div><div><strong>陈晓雨</strong><small>女儿 · 短信、应用通知</small></div><span>备选</span><ChevronRight size={19} /></article></section><section className="contact-policy"><ShieldCheck size={25} /><div><h3>本地联系策略</h3><p>联系人资料不会上传到云端。紧急通知由家庭设备在本地加密触发与发送。</p></div></section></div></PageFrame>
}
