"""Validate the complete medication-reminder acceptance trace.

The trace is generated by an API/integration run and intentionally stores only
event IDs, statuses and evidence references.  It must cover confirmation,
deferral, missed dose, course end, escalation and caregiver escalation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

REQUIRED_SCENARIOS = {
    "confirm",
    "defer",
    "missed",
    "course_end",
    "escalation",
    "caregiver_escalation",
}
EXPECTED_EVENTS = {
    "confirm": {"plan_confirmed"},
    "defer": {"plan_deferred"},
    "missed": {"plan_missed"},
    "course_end": {"course_ended", "plan_completed"},
    "escalation": {"plan_missed", "care_level_escalated", "care_escalated"},
    "caregiver_escalation": {"care_level_escalated", "care_escalated", "caregiver_notified"},
}


def load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("acceptance trace root must be an object")
    return value


def evaluate_trace(trace: dict[str, Any], *, allow_synthetic: bool = False) -> dict[str, Any]:
    findings: list[dict[str, str]] = []
    scope = trace.get("execution_scope")
    if scope not in {"approved_local_api", "synthetic_fixture_only"}:
        findings.append(
            {"code": "INVALID_EXECUTION_SCOPE", "message": "execution_scope is invalid"}
        )
    if scope == "synthetic_fixture_only" and not allow_synthetic:
        findings.append(
            {
                "code": "SYNTHETIC_NOT_ALLOWED",
                "message": "synthetic trace requires --allow-synthetic",
            }
        )
    scenarios = trace.get("scenarios")
    if not isinstance(scenarios, list):
        findings.append({"code": "SCENARIOS_MISSING", "message": "scenarios must be a list"})
        scenarios = []
    by_id: dict[str, dict[str, Any]] = {}
    for item in scenarios:
        if not isinstance(item, dict):
            findings.append({"code": "INVALID_SCENARIO", "message": "scenario must be an object"})
            continue
        scenario_id = str(item.get("scenario_id", "")).strip()
        if not scenario_id or scenario_id in by_id:
            findings.append(
                {
                    "code": "DUPLICATE_SCENARIO",
                    "message": f"invalid or duplicate scenario {scenario_id}",
                }
            )
            continue
        by_id[scenario_id] = item
        if item.get("result") != "PASS":
            findings.append(
                {"code": "SCENARIO_FAILED", "message": f"{scenario_id} result is not PASS"}
            )
        if not str(item.get("evidence_ref", "")).strip():
            findings.append(
                {
                    "code": "EVIDENCE_REF_MISSING",
                    "message": f"{scenario_id} evidence_ref is required",
                }
            )
        events = {str(event) for event in item.get("event_types", [])}
        if scenario_id in EXPECTED_EVENTS and not (events & EXPECTED_EVENTS[scenario_id]):
            findings.append(
                {
                    "code": "EVENT_ASSERTION_MISSING",
                    "message": f"{scenario_id} has no expected event",
                }
            )
        if scenario_id == "caregiver_escalation" and item.get("caregiver_notification") is not True:
            findings.append(
                {
                    "code": "CAREGIVER_NOTIFICATION_MISSING",
                    "message": "caregiver escalation must prove notification",
                }
            )
        if not isinstance(item.get("assertions"), list) or not item["assertions"]:
            findings.append(
                {"code": "ASSERTIONS_MISSING", "message": f"{scenario_id} assertions are required"}
            )

    missing = sorted(REQUIRED_SCENARIOS - set(by_id))
    for scenario_id in missing:
        findings.append({"code": "REQUIRED_SCENARIO_MISSING", "message": f"missing {scenario_id}"})
    passed = not findings and scope == "approved_local_api"
    return {
        "schema_version": "hct308-reminder-acceptance/v1",
        "execution_scope": scope,
        "scenario_count": len(scenarios),
        "required_scenarios": sorted(REQUIRED_SCENARIOS),
        "passed": passed,
        "decision": "ACCEPT_REMINDER_FLOW" if passed else "BLOCK_REMINDER_ACCEPTANCE",
        "findings": findings,
        "limitations": [
            "The trace proves the local API event chain and adapter evidence supplied "
            "by the runner.",
            "It does not prove device delivery unless a delivery evidence_ref is attached.",
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--trace", required=True, type=Path)
    parser.add_argument("--allow-synthetic", action="store_true")
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    try:
        report = evaluate_trace(load(args.trace), allow_synthetic=args.allow_synthetic)
        report["input_sha256"] = hashlib.sha256(args.trace.read_bytes()).hexdigest()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        report = {
            "schema_version": "hct308-reminder-acceptance/v1",
            "passed": False,
            "decision": "BLOCK_REMINDER_ACCEPTANCE",
            "findings": [{"code": "INPUT_ERROR", "message": str(exc)}],
        }
        print(json.dumps(report, ensure_ascii=False, indent=2))
        return 2
    payload = json.dumps(report, ensure_ascii=False, indent=2) + "\n"
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(payload, encoding="utf-8")
    print(payload, end="")
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
